/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import SceneMatchParent from "./scripts/lib/SceneMatchParent"
import UISafeArea from "./scripts/lib/UISafeArea"
import UIScaleFit from "./scripts/lib/UIScaleFit"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="views/start.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scripts/lib/SceneMatchParent.ts",SceneMatchParent);
        reg("scripts/lib/UISafeArea.ts",UISafeArea);
        reg("scripts/lib/UIScaleFit.ts",UIScaleFit);
    }
}
GameConfig.init();